FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . ./

ARG VITE_HOST_IP
ARG VITE_HTTP_PROTOCOL
ARG VITE_WS_PROTOCOL
ARG VITE_HOST_BACKEND_PORT
ARG VITE_HOST_FRONTEND_PORT

ENV VITE_HOST_IP=$VITE_HOST_IP
ENV VITE_HTTP_PROTOCOL=$VITE_HTTP_PROTOCOL
ENV VITE_WS_PROTOCOL=$VITE_WS_PROTOCOL
ENV VITE_HOST_BACKEND_PORT=$VITE_HOST_BACKEND_PORT
ENV VITE_HOST_FRONTEND_PORT=$VITE_HOST_FRONTEND_PORT

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "preview", "--", "--host", "--port", "3000"]